version: "3.8"
services:
  db:
    image: postgres:16
    container_name: db_app
    healthcheck:
      test: pg_isready -h db -p 1221
      interval: 5s
      timeout: 10s
      retries: 3
    command:
      -p 1221
    expose:
      - 1221
    env_file:
      - .env
    networks:
      - custom

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: shift_app
    command: ["/SHIFT_app/docker/app.sh"]
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - custom

networks:
  custom:
    driver: bridge