"""add salarys table

Revision ID: a331f85268f1
Revises: 9ab642111004
Create Date: 2024-05-11 20:52:09.770364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a331f85268f1'
down_revision: Union[str, None] = '9ab642111004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salary_level', sa.Integer(), nullable=False),
    sa.Column('promotion_date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salary')
    # ### end Alembic commands ###
